### PR TITLE
The Polygon Quote mapping did not change

### PR DESCRIPTION
**Pull request by shlomikushchi**
we need to use the same mapping as before

### CODE REVIEW

**Comment by umitanuki** [comment]
@gnvk

**Comment by gnvk** [comment]
@shlomikushchi my bad, the polygon mapping didn't change indeed, but the new endpoint's mapping is different. This PR will break that.  We need to use different mappings for the two.

**Comment by shlomikushchi** [comment]
@gnvk ok, let me know when you get the right mapping. 
right now the backtrader integration is not working with 0.47rc2 so I hope this will help resolve that too

> @shlomikushchi my bad, the polygon mapping didn't change indeed, but the new endpoint's mapping is different. This PR will break that. We need to use different mappings for the two.

**Comment by gnvk** [comment]
I'll merge this and then fix the new endpoint in a separate PR.

**Pull request merged**
